# Generated by Django 4.2.6 on 2023-11-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug_name",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
